import main.LinkTinderMain

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */


class App {
    String getGreeting() {
        return 'Hello world.'
    }

    static void main(String[] args) {
        new LinkTinderMain()
    }
}
