/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Groovy project to get you started.
 * For more details take a look at the Groovy Quickstart chapter in the Gradle
 * user guide available at https://docs.gradle.org/5.1.1/userguide/tutorial_groovy_projects.html
 */

plugins {
    // Apply the groovy plugin to add support for Groovy
    groovy

    // Apply the application plugin to add support for building an application
    application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Use the latest Groovy version for building this library
    implementation("org.codehaus.groovy:groovy-all:2.5.4")
    implementation ("mysql:mysql-connector-java:8.0.28")
    implementation ("org.postgresql:postgresql:42.2.18")
    testImplementation("junit:junit:4.12")

}

application {
    // Define the main class for the application
    mainClassName = "LinkTinder"
}
